# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad6e2a3270ffe43f80b76768517fea5fafff3b532cc7b0c861eb30bc45fd643117abf625b7125f21f143bb1b6010c98823bbee50b5e9018d9c0374b06d3dd08a

test:
  secret_key_base: 10da047544b5de975472194845ff5331de38eae90b9474e00717daad853661e73850d0880df440a090d64bbead373acf84e1caaf17b5245d731425ff98b395bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
